import type { Props } from '..';

export const data: Props = {
  song: {
    artists: [
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/00me4Ke1LsvMxt5kydlMyU',
        },
        href: 'https://api.spotify.com/v1/artists/00me4Ke1LsvMxt5kydlMyU',
        id: '00me4Ke1LsvMxt5kydlMyU',
        name: 'Cosculluela',
        type: 'artist',
        uri: 'spotify:artist:00me4Ke1LsvMxt5kydlMyU',
      },
      {
        external_urls: {
          spotify: 'https://open.spotify.com/artist/7Bb4i0RT3zaudzb8KvxTUQ',
        },
        href: 'https://api.spotify.com/v1/artists/7Bb4i0RT3zaudzb8KvxTUQ',
        id: '7Bb4i0RT3zaudzb8KvxTUQ',
        name: 'Amarion',
        type: 'artist',
        uri: 'spotify:artist:7Bb4i0RT3zaudzb8KvxTUQ',
      },
    ],
    available_markets: [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
      'JP',
      'TH',
      'VN',
      'RO',
      'IL',
      'ZA',
      'SA',
      'AE',
      'BH',
      'QA',
      'OM',
      'KW',
      'EG',
      'MA',
      'DZ',
      'TN',
      'LB',
      'JO',
      'PS',
      'IN',
      'BY',
      'KZ',
      'MD',
      'UA',
      'AL',
      'BA',
      'HR',
      'ME',
      'MK',
      'RS',
      'SI',
      'KR',
      'BD',
      'PK',
      'LK',
      'GH',
      'KE',
      'NG',
      'TZ',
      'UG',
      'AG',
      'AM',
      'BS',
      'BB',
      'BZ',
      'BT',
      'BW',
      'BF',
      'CV',
      'CW',
      'DM',
      'FJ',
      'GM',
      'GE',
      'GD',
      'GW',
      'GY',
      'HT',
      'JM',
      'KI',
      'LS',
      'LR',
      'MW',
      'MV',
      'ML',
      'MH',
      'FM',
      'NA',
      'NR',
      'NE',
      'PW',
      'PG',
      'WS',
      'SM',
      'ST',
      'SN',
      'SC',
      'SL',
      'SB',
      'KN',
      'LC',
      'VC',
      'SR',
      'TL',
      'TO',
      'TT',
      'TV',
      'VU',
      'AZ',
      'BN',
      'BI',
      'KH',
      'CM',
      'TD',
      'KM',
      'GQ',
      'SZ',
      'GA',
      'GN',
      'KG',
      'LA',
      'MO',
      'MR',
      'MN',
      'NP',
      'RW',
      'TG',
      'UZ',
      'ZW',
      'BJ',
      'MG',
      'MU',
      'MZ',
      'AO',
      'CI',
      'DJ',
      'ZM',
      'CD',
      'CG',
      'IQ',
      'LY',
      'TJ',
      'VE',
      'ET',
      'XK',
    ],
    disc_number: 1,
    duration_ms: 217931,
    explicit: false,
    external_urls: {
      spotify: 'https://open.spotify.com/track/1dmrw9I6dWEoELAnZM5ONV',
    },
    href: 'https://api.spotify.com/v1/tracks/1dmrw9I6dWEoELAnZM5ONV',
    id: '1dmrw9I6dWEoELAnZM5ONV',
    is_local: false,
    name: 'Duki',
    preview_url:
      'https://p.scdn.co/mp3-preview/240af3d177094ceab74efbd3b09efcdbf2591314?cid=a0ae1c3cdd864b528713964f561de24e',
    track_number: 1,
    type: 'track',
    uri: 'spotify:track:1dmrw9I6dWEoELAnZM5ONV',
  },
};
